In [5]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [10]:
A=np.random.randn(100)

In [13]:
A

array([ 1.20636091,  1.25801679, -0.16404882, -0.68402895, -0.3201757 ,
       -0.69500748, -0.03498436,  1.02274172, -0.07617764, -0.54380348,
        0.69538919,  0.48469462,  0.3481914 ,  0.68769013,  1.86582355,
        0.253753  , -1.40816079, -0.09233208, -0.41309778, -0.09964317,
       -1.29373034, -0.15885776,  0.62901404,  1.67608769,  0.98502947,
        0.24339882,  1.3256384 ,  0.6947665 , -0.73103696, -1.38331567,
        2.00887239,  0.76550642,  0.19885214,  0.36268954, -0.18315511,
       -1.17025831,  0.41311342,  0.06303722, -0.79327359,  0.44276348,
        0.44257959, -0.56448973, -0.20489773, -0.43195143,  0.93807962,
        1.63242055, -1.13861486, -1.74220384,  0.21800557,  0.50558754,
       -1.40080197, -1.21744857,  1.60850425, -1.69720564,  1.72575475,
        0.77265447,  2.07948442, -1.15287015,  0.12042332,  0.61338877,
       -1.49086198, -0.17758441,  0.33880194,  0.4836274 , -0.5397793 ,
       -0.91389319,  0.76354636, -0.02452105, -1.19539357,  0.24

In [14]:
A=10*A+50

In [15]:
A

array([62.06360906, 62.58016788, 48.35951179, 43.1597105 , 46.79824305,
       43.04992521, 49.65015635, 60.22741722, 49.23822361, 44.56196523,
       56.95389186, 54.84694623, 53.48191404, 56.87690132, 68.6582355 ,
       52.53752997, 35.91839209, 49.07667919, 45.86902217, 49.00356832,
       37.06269661, 48.41142241, 56.29014036, 66.76087694, 59.85029467,
       52.43398817, 63.25638404, 56.94766503, 42.68963038, 36.16684333,
       70.08872391, 57.65506423, 51.98852138, 53.62689537, 48.16844891,
       38.29741687, 54.13113422, 50.63037215, 42.06726409, 54.42763477,
       54.42579591, 44.35510267, 47.95102272, 45.68048565, 59.38079615,
       66.32420554, 38.61385143, 32.57796165, 52.18005568, 55.05587541,
       35.99198025, 37.82551432, 66.0850425 , 33.02794359, 67.25754746,
       57.72654473, 70.79484415, 38.47129848, 51.20423323, 56.13388768,
       35.09138024, 48.22415594, 53.38801939, 54.836274  , 44.60220697,
       40.86106811, 57.63546359, 49.75478946, 38.04606433, 52.44

In [16]:
A.shape

(100,)

In [17]:
A.shape=(5,20)

In [18]:
A

array([[62.06360906, 62.58016788, 48.35951179, 43.1597105 , 46.79824305,
        43.04992521, 49.65015635, 60.22741722, 49.23822361, 44.56196523,
        56.95389186, 54.84694623, 53.48191404, 56.87690132, 68.6582355 ,
        52.53752997, 35.91839209, 49.07667919, 45.86902217, 49.00356832],
       [37.06269661, 48.41142241, 56.29014036, 66.76087694, 59.85029467,
        52.43398817, 63.25638404, 56.94766503, 42.68963038, 36.16684333,
        70.08872391, 57.65506423, 51.98852138, 53.62689537, 48.16844891,
        38.29741687, 54.13113422, 50.63037215, 42.06726409, 54.42763477],
       [54.42579591, 44.35510267, 47.95102272, 45.68048565, 59.38079615,
        66.32420554, 38.61385143, 32.57796165, 52.18005568, 55.05587541,
        35.99198025, 37.82551432, 66.0850425 , 33.02794359, 67.25754746,
        57.72654473, 70.79484415, 38.47129848, 51.20423323, 56.13388768],
       [35.09138024, 48.22415594, 53.38801939, 54.836274  , 44.60220697,
        40.86106811, 57.63546359, 49.75478946, 3

In [19]:
A.reshape(100,1)

array([[62.06360906],
       [62.58016788],
       [48.35951179],
       [43.1597105 ],
       [46.79824305],
       [43.04992521],
       [49.65015635],
       [60.22741722],
       [49.23822361],
       [44.56196523],
       [56.95389186],
       [54.84694623],
       [53.48191404],
       [56.87690132],
       [68.6582355 ],
       [52.53752997],
       [35.91839209],
       [49.07667919],
       [45.86902217],
       [49.00356832],
       [37.06269661],
       [48.41142241],
       [56.29014036],
       [66.76087694],
       [59.85029467],
       [52.43398817],
       [63.25638404],
       [56.94766503],
       [42.68963038],
       [36.16684333],
       [70.08872391],
       [57.65506423],
       [51.98852138],
       [53.62689537],
       [48.16844891],
       [38.29741687],
       [54.13113422],
       [50.63037215],
       [42.06726409],
       [54.42763477],
       [54.42579591],
       [44.35510267],
       [47.95102272],
       [45.68048565],
       [59.38079615],
       [66

In [20]:
A

array([[62.06360906, 62.58016788, 48.35951179, 43.1597105 , 46.79824305,
        43.04992521, 49.65015635, 60.22741722, 49.23822361, 44.56196523,
        56.95389186, 54.84694623, 53.48191404, 56.87690132, 68.6582355 ,
        52.53752997, 35.91839209, 49.07667919, 45.86902217, 49.00356832],
       [37.06269661, 48.41142241, 56.29014036, 66.76087694, 59.85029467,
        52.43398817, 63.25638404, 56.94766503, 42.68963038, 36.16684333,
        70.08872391, 57.65506423, 51.98852138, 53.62689537, 48.16844891,
        38.29741687, 54.13113422, 50.63037215, 42.06726409, 54.42763477],
       [54.42579591, 44.35510267, 47.95102272, 45.68048565, 59.38079615,
        66.32420554, 38.61385143, 32.57796165, 52.18005568, 55.05587541,
        35.99198025, 37.82551432, 66.0850425 , 33.02794359, 67.25754746,
        57.72654473, 70.79484415, 38.47129848, 51.20423323, 56.13388768],
       [35.09138024, 48.22415594, 53.38801939, 54.836274  , 44.60220697,
        40.86106811, 57.63546359, 49.75478946, 3

In [21]:
A=A.reshape(100,1)

In [22]:
A

array([[62.06360906],
       [62.58016788],
       [48.35951179],
       [43.1597105 ],
       [46.79824305],
       [43.04992521],
       [49.65015635],
       [60.22741722],
       [49.23822361],
       [44.56196523],
       [56.95389186],
       [54.84694623],
       [53.48191404],
       [56.87690132],
       [68.6582355 ],
       [52.53752997],
       [35.91839209],
       [49.07667919],
       [45.86902217],
       [49.00356832],
       [37.06269661],
       [48.41142241],
       [56.29014036],
       [66.76087694],
       [59.85029467],
       [52.43398817],
       [63.25638404],
       [56.94766503],
       [42.68963038],
       [36.16684333],
       [70.08872391],
       [57.65506423],
       [51.98852138],
       [53.62689537],
       [48.16844891],
       [38.29741687],
       [54.13113422],
       [50.63037215],
       [42.06726409],
       [54.42763477],
       [54.42579591],
       [44.35510267],
       [47.95102272],
       [45.68048565],
       [59.38079615],
       [66